%% SYSTEM-WIDE ENERGY ANALYSIS 
% Calculates Net Energy entering/leaving the capacitor bank and Average Source Power.
clear; clc; close all;

% --- 1. SETUP ---
fileName = 'Global_ft2b.mat'; 
if ~isfile(fileName), error('File %s not found.', fileName); end
fprintf('Loading data from %s...\n', fileName);
load(fileName, 'GlobalData');

% Capacitor Values (Farad)
C_out  = 240e-3; 
C_bT   = 120e-3; 
C_bP   = 33e-3;

% Shunt Resistors (Ohm)
R_shunt_TEG = 0.2;
R_shunt_PV  = 10.0;

% Op-Amp Gains (V/V)
Gain_TEG = 113.0;
Gain_PV  = 46.0;

% Smoothing window for energy derivation (adjust based on noise level)
smooth_win = 100; 

% --- 2. CALCULATE REAL CURRENTS & POWER ---
% Convert Shunt Voltage to Current (I = V/R) using UPDATED variable names
I_TEG_real = GlobalData.Vcurr_TEG / (R_shunt_TEG*Gain_TEG);
I_PV_real  = GlobalData.Vcurr_PV  / (R_shunt_PV*Gain_PV);

% Calculate Instantaneous Power (P = V_source * I_real)
P_inst_TEG = GlobalData.V_TEG .* I_TEG_real;
P_inst_PV  = GlobalData.V_PV  .* I_PV_real;

% --- NEW: CALCULATE AVERAGE POWER ---
% Mean power over the entire measurement duration
Avg_Power_TEG = mean(P_inst_TEG);
Avg_Power_PV  = mean(P_inst_PV);

% --- 3. CALCULATE TOTAL INSTANTANEOUS ENERGY (STORED) ---
% Sum of energy in ALL capacitors (C_out + C_batt_sec)
% Using UPDATED variable names for battery voltages

E_Cout = 0.5 * C_out * GlobalData.Vout.^2;
E_CbT  = 0.5 * C_bT  * GlobalData.Vbatt_sec_TEG.^2;
E_CbP  = 0.5 * C_bP  * GlobalData.Vbatt_sec_PV.^2;

% Total System Energy Curve
E_System_Raw = E_Cout + E_CbT + E_CbP;

% Smooth data to remove ADC noise before differentiation
E_System = smoothdata(E_System_Raw, 'gaussian', smooth_win);

% --- 4. CALCULATE FLUXES (NET CHARGE vs DISCHARGE) ---
% dE > 0: Energy entering the system (Harvested)
% dE < 0: Energy leaving the system (Load/Losses)

dE_Sys = [0; diff(E_System)];

% Sum positive increments (Total Energy entered storage)
Total_Energy_Harvested = sum(dE_Sys(dE_Sys > 0));

% Sum negative increments (Total Energy delivered to load)
Total_Energy_Delivered = abs(sum(dE_Sys(dE_Sys < 0)));

% --- 5. SOURCE ENERGY (INPUT INTEGRAL) ---
% Total Energy generated by sources (Integral of Power)
E_Source_TEG = trapz(seconds(GlobalData.Time), P_inst_TEG);
E_Source_PV  = trapz(seconds(GlobalData.Time), P_inst_PV);
E_Source_Total = E_Source_TEG + E_Source_PV;

% Storage Efficiency
Storage_Efficiency = (Total_Energy_Harvested / E_Source_Total) * 100;

% --- 6. REPORT ---
fprintf('\n==================================================\n');
fprintf('       SYSTEM-WIDE ENERGY & POWER REPORT\n');
fprintf('==================================================\n');

fprintf('1. AVERAGE POWER (Mean over full duration)\n');
fprintf('   Avg Power TEG:            %10.6f W  (%.2f mW)\n', Avg_Power_TEG, Avg_Power_TEG*1000);
fprintf('   Avg Power PV:             %10.6f W  (%.2f mW)\n', Avg_Power_PV, Avg_Power_PV*1000);
fprintf('   ----------------------------------------------\n');

fprintf('2. TOTAL ENERGY GENERATED (Input)\n');
fprintf('   Energy from TEG:          %10.6f J\n', E_Source_TEG);
fprintf('   Energy from PV:           %10.6f J\n', E_Source_PV);
fprintf('   TOTAL SOURCE ENERGY:      %10.6f J\n', E_Source_Total);
fprintf('\n');

fprintf('3. STORAGE SYSTEM (C_out + C_bT + C_bP)\n');
fprintf('   Total Energy ACCUMULATED: %10.6f J\n', Total_Energy_Harvested);
fprintf('   (Net energy effectively stored in capacitor bank)\n');
fprintf('\n');

fprintf('4. LOAD (OUTPUT)\n');
fprintf('   Total Energy DELIVERED:   %10.6f J\n', Total_Energy_Delivered);
fprintf('   (Energy discharged to load + system leakage)\n');
fprintf('\n');

fprintf('5. EFFICIENCY\n');
fprintf('   Storage Efficiency:       %.2f %%\n', Storage_Efficiency);
fprintf('==================================================\n');

% --- 7. PLOTS ---
figure('Name', 'Power and Energy Analysis', 'Color', 'w');

subplot(3,1,1);
plot(GlobalData.Time, P_inst_TEG*1000, 'r'); hold on;
plot(GlobalData.Time, P_inst_PV*1000, 'b');
yline(Avg_Power_TEG*1000, 'r--', 'LineWidth', 2);
yline(Avg_Power_PV*1000, 'b--', 'LineWidth', 2);
ylabel('Power (mW)');
legend('Inst. TEG', 'Inst. PV', 'Avg TEG', 'Avg PV');
title('Source Power Generation'); grid on;

subplot(3,1,2);
plot(GlobalData.Time, GlobalData.Vout, 'k'); hold on;
plot(GlobalData.Time, GlobalData.Vbatt_sec_TEG, 'r--');
plot(GlobalData.Time, GlobalData.Vbatt_sec_PV, 'b--');
ylabel('Voltage (V)');
legend('Vout', 'Vbatt TEG', 'Vbatt PV');
title('System Voltages'); grid on;

subplot(3,1,3);
plot(GlobalData.Time, E_System, 'm', 'LineWidth', 1.5);
ylabel('Energy (J)');
title('Total System Stored Energy (Sum of all Caps)'); grid on;